### PR TITLE
added js

### PR DESCRIPTION
**Pull request by cecerodrgz**

### CODE REVIEW

**Comment by Jkuffler** [comment]
`[ ] Above the "Connect" section, add a new <section> element with an id attribute of value "skills"
[ ] Inside the new section, add a <h2> element that says "Skills"
[ ] After the <h2> element, add an empty unordered list (<ul>) element`

make sure to get the skills section into your HTML file so that when the script is running it won't return errors. See above. Don't worry - it happens to us all. I don't see any other problems. Feel free to follow up on slack or during a session :)

**Comment by cecerodrgz** [comment]
I thought it had it, but I had some other issues with the repository, and I am guessing that is what happened. However, I do have a question, does the index.html have to have the Skills written down or they should show with what I did on the index.js; for some reason it isn't showing at all once I had it deleted, so I am wondering if that is what I have wrong.

**Comment by Jkuffler** [comment]
`    const skill = document.createElement('li');` the line that you have that code is where the li is created for the DOM. 

this `for `loop (below) that you have is where the DOM will render each skill/`<li>` into the browser. It's how the javascript language is used to create and manipulate HTML elements / DOM nodes. If you're still having trouble seeing them render to the browser then check where you're setting the value of each skill. It could be that the innerHTML method is picky about what data it gets assigned to. Let me know next time you come back to this part if I can help any further
```
for (let i = 0; i < skills.length; i++) {
    const skill = document.createElement('li');
    skill.innerHTML = skills[i];
    skillsList.appendChild(skill);
};
```

**Comment by cecerodrgz** [comment]
Not sure where I went wrong, but now I can't see my js folder when I try to inspect the page on the website to check what is not functioning well.

**Pull request merged**
